# -*- coding: utf-8 -*-
"""statins_mod.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwevGKLnujBygBrXtg4ldITTwHFPs3Y-
"""

from google.colab import files

# Import the dependecies
import requests
import pandas as pd
import json
from requests.structures import CaseInsensitiveDict
import time

import ssl

ssl._create_default_https_context = ssl._create_unverified_context

def mod_df(url_df, url_reactions, num, drugname):
	
	name_df = pd.read_csv(url_df)
 
	name_df.drop(columns='Unnamed: 0',inplace=True)

	df_reactions = pd.read_csv(url_reactions)
 
	df_reactions.rename(columns={"Unnamed: 0":"reactions"}, inplace=True)
 
	reactions = df_reactions.head(10)['reactions'].tolist()
	 
	for r in reactions:
		name_df[r] = 0
		
	reactions_df1 = []
	for col in name_df.columns:
	  if "reactionmeddrapt" in col:
		  reactions_df1.append(col)
		
	outcome_df1 = []
	for col in name_df.columns:
		if "reactionoutcome" in col:
			outcome_df1.append(col)
		
	for r in reactions:
		for col in reactions_df1:
			name_df.loc[name_df[col] == r, r] = 1
			
	for r in reactions:
		print(name_df[r].value_counts())
		
	for col in reactions_df1:
		name_df.drop(columns=col,inplace=True)
		
	for col in outcome_df1:
		name_df.drop(columns=col,inplace=True)
	
	for column in name_df.columns:
		print(f"Column {column} has {name_df[column].isnull().sum()} null values")
		
	output_file = f'df_{drugname}_{num}_reactions_md.csv'
	
	name_df.to_csv(output_file)
	
	files.download(output_file)