# -*- coding: utf-8 -*-
"""statinees_drug_reactions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CoVBV0coUtdymu-gCQ760NDz4fbxrbtz

The code in this notebook is to find the reactions reported in each dataframe created for a drug. The results are saved in a dataframe where the reactions are odered in descending order. Then the results for each dataframe is merged to get the reactions most found in them. The result is saved in a file.
"""

# Import the dependecies
from google.colab import files
import requests
import pandas as pd
import json
from requests.structures import CaseInsensitiveDict
import time

import ssl

ssl._create_default_https_context = ssl._create_unverified_context

def get_reactions(url):
  df_sample = pd.read_csv(url)

  cols_reaction = []

  for col in df_sample.columns:
    if "reactionmeddrapt" in col:
      cols_reaction.append(col)

  dict_reactions = {}
  for col in cols_reaction:
    dicto = df_sample[col].value_counts().to_dict()
    for k in dicto:
      if k not in dict_reactions:
        dict_reactions[k] = int(dicto[k])
      else:
        dict_reactions[k] = dict_reactions[k] + int(dicto[k])

  df_sample_reactions = pd.DataFrame.from_dict(dict_reactions, orient='index',
                        columns=['n'])
  df_sample_reactions = df_sample_reactions.sort_values(by='n',ascending=False)

  return df_sample_reactions

def get_reactions_death(url):

  df = pd.read_csv(url)

  df_sample = df[df['seriousnessdeath']== 1]
  
  cols_reaction = []

  for col in df_sample.columns:
    if "reactionmeddrapt" in col:
      cols_reaction.append(col)

  dict_reactions = {}
  for col in cols_reaction:
    dicto = df_sample[col].value_counts().to_dict()
    for k in dicto:
      if k not in dict_reactions:
        dict_reactions[k] = int(dicto[k])
      else:
        dict_reactions[k] = dict_reactions[k] + int(dicto[k])

  df_sample_reactions = pd.DataFrame.from_dict(dict_reactions, orient='index',
                        columns=['n'])
  df_sample_reactions = df_sample_reactions.sort_values(by='n',ascending=False)

  return df_sample_reactions

def get_reactions_hosp(url):

  df = pd.read_csv(url)

  df_sample = df[df['seriousnesshospitalization']== 1]
  
  cols_reaction = []

  for col in df_sample.columns:
    if "reactionmeddrapt" in col:
      cols_reaction.append(col)

  dict_reactions = {}
  for col in cols_reaction:
    dicto = df_sample[col].value_counts().to_dict()
    for k in dicto:
      if k not in dict_reactions:
        dict_reactions[k] = int(dicto[k])
      else:
        dict_reactions[k] = dict_reactions[k] + int(dicto[k])

  df_sample_reactions = pd.DataFrame.from_dict(dict_reactions, orient='index',
                        columns=['n'])
  df_sample_reactions = df_sample_reactions.sort_values(by='n',ascending=False)

  return df_sample_reactions